### ISSUE TITLE
FPS drops to 30 after disabling headset

### ISSUE THREAD

**Issue by LRitesh** [n1ckfg/ViveTrackerExample#1]
Hi there,

First of all thanks for putting this up, it's super helpful! I managed to get a tracker working without the headset following your instructions. But now my app seems to run at 30fps. I've made sure to disable VSync everywhere and the screen I have runs at 120Hz. Before disabling the headset I could get upto 90fps. I was wondering if you ran into this issue at all. If I remove XR Support from the Player Settings (which uninstalls OpenVR), I seem to get 120Hz, but ofcourse then I can't use the trackers.

Any ideas?

(Also does your example run with a specific version of Unity? I can't get it to open with Unity 2017.3.1 and 2018.3.0f2).

Thanks,
Ritesh

**Comment by n1ckfg** [comment]
Try using the SteamVR plugin--in my experience the built-in Unity support has issues with controllers. Iirc tested on 2017.4 and 2018.1.

**Comment by LRitesh** [comment]
I am actually using SteamVR (but apparently it still requires OpenVR to run? I guess it's a wrapper for OpenVR). Cool I'll test out with those versions. Thanks for the quick response.

**Comment by LRitesh** [comment]
I ended up not sending tracker pose data over UDP to Unity and taking out any OpenVR dependencies altogether from inside Unity. This fixed the FPS issue for me.
